spring:
  datasource:
    url: jdbc:h2:mem:vehicledb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

springdoc:
  api-docs:
    path: /api-docs
